#!/usr/bin/env bash
# Configures NGINX
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World" > /var/www/coderlancce.tech/html/index.html
new_string="server_name _;\nlocation ~ /redirect_me/$ {
rewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx restart
