#!/usr/bin/env bash
# This script is displaying "Best School" 10
# times but for the 9th iteration, displays
# Best School and then Hi on a new line.
i=0
TEXT="Best School"
while [ $i -le 9 ]
do
	if [ $i -ne 8 ]
	then
		echo "$TEXT"
	else
		echo -e "Best School\nHi"
	fi
	i=$((i + 1))
done
